python3 perturbation.py --config_path             configs/cifar100                \
                        --exp_name                /data/yfwang/Unlearnable/logs/cifar100/minimin \
                        --version                 resnet18                       \
                        --train_data_type         CIFAR100                       \
                        --test_data_type          CIFAR100                       \
                        --noise_shape             50000 3 32 32                  \
                        --epsilon                 8                              \
                        --num_steps               20                             \
                        --step_size               0.8                            \
                        --attack_type             min-min                        \
                        --perturb_type            samplewise                      \
                        --universal_stop_error    0.01                            \
                        --train_step              20                              \
                        --random_start
